CREATE TABLE IF NOT EXISTS "Users" (
  "UserId" TEXT PRIMARY KEY,
  "Username" TEXT NOT NULL DEFAULT '',
  "Email" TEXT NOT NULL DEFAULT '',
  "Role" TEXT NOT NULL DEFAULT 'User',
  "Department" TEXT NOT NULL DEFAULT '',
  "CreatedAt" TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "Assets" (
  "AssetId" TEXT PRIMARY KEY,
  "Name" TEXT NOT NULL DEFAULT '',
  "AssetCode" TEXT NOT NULL DEFAULT '',
  "Category" TEXT NOT NULL DEFAULT '',
  "Location" TEXT NOT NULL DEFAULT '',
  "Status" TEXT NOT NULL DEFAULT 'Active',
  "OwnerId" TEXT NOT NULL DEFAULT '',
  "CreatedAt" TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "Transfers" (
  "Id" TEXT PRIMARY KEY,
  "AssetId" TEXT NOT NULL DEFAULT '',
  "ToUserId" TEXT NOT NULL DEFAULT '',
  "Reason" TEXT NOT NULL DEFAULT '',
  "TransferDate" TIMESTAMP NOT NULL DEFAULT NOW()
);
