"""Add code_review document type and code-review-agent seed

Revision ID: 0013
Revises: 0012
Create Date: 2026-06-19
"""
from typing import Sequence, Union

from alembic import op

revision: str = "0013"
down_revision: Union[str, None] = "0012"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_SKILL = """\
# Code Review Agent — Skill Document

## Role
Reviews the code generated by Developer Agent before it reaches DevOps.
Produces a structured code_review.md with severity-classified issues and an
overall PASS / NEEDS_WORK / FAIL verdict.

## Layer
Delivery Layer — Step 7 of 12

## Pipeline Position
Runs after dev_tasks (Developer Agent) and before devops_tasks (DevOps Agent).

## Capabilities
- Scan all files in the generated_app workspace directory
- Detect security vulnerabilities (injection, hardcoded secrets, insecure patterns)
- Identify logic errors, missing error handling, incomplete implementations
- Flag style and maintainability issues
- Verify each TASK from dev_tasks.md was actually implemented
- Produce CR-XXX issues with file, severity, and fix suggestion

## Input Contract
| Source | Details |
|--------|---------|
| workspace generated_app/ | Code files produced by Developer Agent |
| docs/dev_tasks.md | Expected task list (used to check completeness) |

## Output Contract
| File | Description |
|------|-------------|
| docs/code_review.md | CR-XXX issues, verdict, summary statistics |

## Severity Levels
| Level | Meaning |
|-------|---------|
| critical | Security risk or data loss — must fix before deploy |
| major | Broken feature, missing required logic |
| minor | Quality issue, incomplete implementation |
| info | Suggestion or style note |

## Behaviour Notes
- Verdict PASS: 0 critical + 0 major issues
- Verdict NEEDS_WORK: 0 critical, >= 1 major issues
- Verdict FAIL: >= 1 critical issue
- Model: qwen3:8b
"""


def upgrade() -> None:
    op.execute("ALTER TYPE document_type ADD VALUE IF NOT EXISTS 'code_review'")

    escaped = _SKILL.replace("'", "''")
    op.execute(f"""
        INSERT INTO agents (name, role, home_zone, current_zone, model_provider, model_name, status, is_active, skill_markdown)
        VALUES (
            'code-review-agent', 'code_reviewer',
            'delivery_room', 'delivery_room',
            'ollama', 'qwen3:8b', 'idle', true,
            '{escaped}'
        )
        ON CONFLICT (name) DO NOTHING
    """)


def downgrade() -> None:
    op.execute("DELETE FROM agents WHERE name = 'code-review-agent'")
