"""DevOps Agent -- Pipeline Step 7.

Reads the Architecture Design, Database Design, and API Spec to generate
real deployment and infrastructure files for the project.

Output files (predefined for FastAPI + React + PostgreSQL stack):
  Dockerfile.backend
  Dockerfile.frontend
  docker-compose.yml
  docker-compose.prod.yml
  nginx.conf
  .env.example
  .github/workflows/ci.yml
  README.md

Files are written to: {workspace}/generated_app/  (same folder as dev_agent)
A summary document (devops_config type) is saved to the DB.
"""
import logging
import os
import re
import uuid
from datetime import UTC, datetime
from typing import Optional

from sqlmodel import Session, select

from app.db.models import (
    ActivityLog,
    Agent,
    AgentStatus,
    Document,
    DocumentStatus,
    DocumentType,
    EventType,
    PipelineRun,
    PipelineRunStatus,
    PipelineStep,
    PipelineStepStatus,
    Project,
)
from app.llm import client as _llm

logger = logging.getLogger(__name__)

AGENT_NAME = "devops-agent"
STEP_NAME  = "devops_tasks"

FILE_TIMEOUT   = 120.0
MIN_FILE_CHARS = 30


def _trunc(s: str, n: int) -> str:
    return s[:n] + "\n...(truncated)" if len(s) > n else s


# -- Predefined file specs ----------------------------------------------------
# (filename, lang hint, context_type)

_DEVOPS_FILES: list[tuple[str, str, str]] = [
    ("Dockerfile.backend",       "dockerfile", "backend_docker"),
    ("Dockerfile.frontend",      "dockerfile", "frontend_docker"),
    ("docker-compose.yml",       "yaml",       "compose_dev"),
    ("docker-compose.prod.yml",  "yaml",       "compose_prod"),
    ("nginx.conf",               "text",       "nginx"),
    (".env.example",             "bash",       "env_example"),
    (".github/workflows/ci.yml", "yaml",       "github_ci"),
    ("README.md",                "markdown",   "readme"),
]

# -- Prompts ------------------------------------------------------------------

_SYSTEM_PROMPT = """\
You are an expert DevOps engineer and infrastructure specialist.
You write clean, production-ready deployment configuration files for
full-stack web applications.

RULES:
- Output ONLY the file content. No markdown fences. No explanation.
- Tech stack: FastAPI (Python 3.11) + PostgreSQL 15 for backend;
  React + Vite + Node 20 for frontend.
- Use multi-stage Docker builds to keep image sizes small.
- docker-compose.yml should include: postgres, redis, backend, frontend, nginx.
- docker-compose.prod.yml should add: resource limits, restart policies,
  volume mounts for persistent data.
- nginx.conf should proxy /api/ to backend:8000 and serve frontend on /.
- .env.example must list ALL environment variables with placeholder values.
- GitHub Actions CI should: checkout, run backend tests (pytest), run frontend
  type-check (tsc --noEmit), build Docker images.
- README.md should explain: prerequisites, quick start, env setup, Docker commands.
- Never hardcode real passwords or secrets -- use placeholder values.
"""

_FILE_TEMPLATE = """\
Generate the complete content of this file:

FILE: {path}
FORMAT: {lang}
PURPOSE: {purpose}

RELEVANT CONTEXT:
{context}

Output the file content directly. No fences, no explanation.
"""

_PURPOSES: dict[str, str] = {
    "backend_docker":  "Multi-stage Dockerfile for FastAPI backend (Python 3.11, uvicorn)",
    "frontend_docker": "Multi-stage Dockerfile for React/Vite frontend (Node 20 build, nginx serve)",
    "compose_dev":     "docker-compose.yml for local development with hot-reload",
    "compose_prod":    "docker-compose.prod.yml for production with resource limits and restart policies",
    "nginx":           "nginx.conf reverse proxy: /api/ → backend:8000, / → frontend static files",
    "env_example":     ".env.example template listing all required environment variables",
    "github_ci":       "GitHub Actions CI workflow: lint, test, type-check, build on push/PR",
    "readme":          "README.md with prerequisites, quick start, environment setup, Docker commands",
}


# -- Markdown summary ---------------------------------------------------------

def _render_summary(
    results: list[tuple[str, bool]],
    project_id: str,
    doc_id: str,
) -> str:
    ok   = sum(1 for _, s in results if s)
    fail = len(results) - ok

    rows = ""
    for path, success in results:
        status = "OK" if success else "FAILED"
        rows += f"| `{path}` | {status} |\n"

    return f"""\
# DevOps Configuration Summary

**Project ID:** `{project_id}`
**Document ID:** `{doc_id}`
**Generated By:** DevOps Agent v1.0.0
**Pipeline Step:** 7 of 10
**Status:** Draft -- Awaiting Review

---

## Generation Results

| Files OK | Files Failed |
|---|---|
| {ok} | {fail} |

## Files Generated

| Path | Status |
|---|---|
{rows}

---

## Output Location

Files are written to: `generated_app/` inside the project workspace.
View and download via the **Generated Code** tab.

{"**Warning:** Some files failed to generate. Review and regenerate manually." if fail else "All deployment files generated successfully."}
"""


# -- Agent runner -------------------------------------------------------------

class DevOpsAgentRunner:
    def __init__(self, session: Session) -> None:
        self.session = session

    def run(self, run_id: uuid.UUID) -> None:
        step: Optional[PipelineStep] = None
        agent_row: Optional[Agent] = None

        try:
            run = self._get_run(run_id)
            if run.status == PipelineRunStatus.failed:
                logger.info("DevOpsAgent skipped -- run %s already failed", run_id)
                return

            step = self._get_step(run_id)
            agent_row = self._get_agent_row()
            model = agent_row.model_name if agent_row else None

            run.status = PipelineRunStatus.running
            run.current_step = STEP_NAME
            step.status = PipelineStepStatus.running
            step.started_at = datetime.now(UTC)
            if agent_row:
                agent_row.status = AgentStatus.working
                agent_row.updated_at = datetime.now(UTC)
            self.session.commit()

            arch_doc, db_doc, api_doc, fsd_doc = self._load_source_documents(run.project_id)
            project = self.session.get(Project, run.project_id)
            project_name = project.name if project else "project"

            docs = {
                "architecture": arch_doc.content_markdown,
                "database":     db_doc.content_markdown,
                "api_spec":     api_doc.content_markdown,
                "fsd":          fsd_doc.content_markdown,
                "project_name": project_name,
            }

            out_dir = self._get_output_dir(run.project_id)
            results: list[tuple[str, bool]] = []

            for path, lang, ctx_type in _DEVOPS_FILES:
                content = self._generate_file(path, lang, ctx_type, docs, model)
                if content:
                    self._write_file(out_dir, path, content)
                    results.append((path, True))
                    logger.info("DevOpsAgent generated %s", path)
                else:
                    results.append((path, False))
                    logger.warning("DevOpsAgent failed to generate %s", path)

            doc_id = uuid.uuid4()
            pid = str(run.project_id)
            summary_md = _render_summary(results, pid, str(doc_id))

            summary_doc = Document(
                id=doc_id,
                project_id=run.project_id,
                document_type=DocumentType.devops_config,
                title="DevOps Configuration Summary",
                content_markdown=summary_md,
                version=1,
                status=DocumentStatus.review,
                created_by_agent_id=agent_row.id if agent_row else None,
            )
            self.session.add(summary_doc)
            self.session.flush()

            step.status = PipelineStepStatus.completed
            step.agent_id = agent_row.id if agent_row else None
            step.output_document_id = summary_doc.id
            step.completed_at = datetime.now(UTC)

            run.status = PipelineRunStatus.waiting_for_user
            run.current_step = STEP_NAME

            if agent_row:
                agent_row.status = AgentStatus.done
                agent_row.updated_at = datetime.now(UTC)

            ok_count = sum(1 for _, s in results if s)
            self._log_activity(
                run.project_id, agent_row,
                f"DevOps configuration generated: {ok_count}/{len(results)} files "
                f"written to generated_app/. Awaiting Gate 6 review.",
            )
            self.session.commit()
            logger.info("DevOpsAgent completed run=%s files=%d/%d", run_id, ok_count, len(results))

        except Exception as exc:
            logger.exception("DevOpsAgent failed run=%s: %s", run_id, exc)
            self.session.rollback()
            try:
                run = self.session.get(PipelineRun, run_id)
                if run:
                    run.status = PipelineRunStatus.failed
                if step:
                    step.status = PipelineStepStatus.failed
                    step.error_message = str(exc)[:2000]
                if agent_row:
                    agent_row.status = AgentStatus.error
                    agent_row.updated_at = datetime.now(UTC)
                self.session.commit()
            except Exception:
                logger.exception("Failed to persist failure state for run=%s", run_id)

    # -- Generation helpers ---------------------------------------------------

    def _generate_file(
        self,
        path: str,
        lang: str,
        ctx_type: str,
        docs: dict[str, str],
        model: str | None,
    ) -> str | None:
        context = self._build_context(ctx_type, docs)
        purpose = _PURPOSES.get(ctx_type, f"Generate {path}")
        prompt = _FILE_TEMPLATE.format(
            path=path, lang=lang, purpose=purpose, context=context,
        )
        for attempt in range(2):
            try:
                raw = _llm.call_ollama(
                    system_prompt=_SYSTEM_PROMPT,
                    user_prompt=prompt,
                    model=model,
                    timeout=FILE_TIMEOUT,
                    response_format=None,
                )
                content = _llm.strip_code_fences(raw)
                if len(content) >= MIN_FILE_CHARS:
                    return content
                logger.warning("DevOps file %s: short output attempt %d", path, attempt + 1)
            except Exception as exc:
                logger.warning("DevOps file %s error attempt %d: %s", path, attempt + 1, exc)
        return None

    def _build_context(self, ctx_type: str, docs: dict[str, str]) -> str:
        arch  = _trunc(docs["architecture"], 3000)
        db    = _trunc(docs["database"], 2000)
        api   = _trunc(docs["api_spec"], 2000)
        fsd   = _trunc(docs["fsd"], 1500)
        pname = docs["project_name"]

        if ctx_type in ("backend_docker", "frontend_docker"):
            return f"PROJECT: {pname}\n\nARCHITECTURE:\n{arch}"
        if ctx_type in ("compose_dev", "compose_prod"):
            return f"PROJECT: {pname}\n\nARCHITECTURE:\n{arch}\n\nDATABASE DESIGN:\n{db}"
        if ctx_type == "nginx":
            return f"PROJECT: {pname}\n\nAPI SPEC (for proxy routing):\n{api}"
        if ctx_type == "env_example":
            return f"PROJECT: {pname}\n\nARCHITECTURE:\n{arch}\n\nDATABASE DESIGN:\n{db}"
        if ctx_type == "github_ci":
            return f"PROJECT: {pname}\n\nARCHITECTURE:\n{arch}"
        if ctx_type == "readme":
            return f"PROJECT: {pname}\n\nFSD EXCERPT:\n{fsd}\n\nARCHITECTURE:\n{arch}"
        return arch

    def _write_file(self, out_dir: str, rel_path: str, content: str) -> None:
        safe_rel = re.sub(r"\.\.+[/\\]", "", rel_path).lstrip("/\\")
        full_path = os.path.join(out_dir, safe_rel)
        os.makedirs(os.path.dirname(full_path), exist_ok=True)
        with open(full_path, "w", encoding="utf-8") as f:
            f.write(content)

    def _get_output_dir(self, project_id: uuid.UUID) -> str:
        project = self.session.get(Project, project_id)
        raw = (project.workspace_path if project else None) or "/workspace"
        container_path = re.sub(
            r"^[A-Za-z]:[/\\]workspace", "/workspace", raw, flags=re.IGNORECASE
        )
        if not container_path.startswith("/workspace"):
            container_path = "/workspace"
        safe_name = re.sub(r"[^\w\-]", "_", project.name if project else "project")
        return os.path.join(container_path, safe_name, "generated_app")

    # -- DB helpers -----------------------------------------------------------

    def _get_run(self, run_id: uuid.UUID) -> PipelineRun:
        run = self.session.get(PipelineRun, run_id)
        if not run:
            raise ValueError(f"PipelineRun {run_id} not found")
        return run

    def _get_step(self, run_id: uuid.UUID) -> PipelineStep:
        step = self.session.exec(
            select(PipelineStep).where(
                PipelineStep.pipeline_run_id == run_id,
                PipelineStep.step_name == STEP_NAME,
            )
        ).first()
        if not step:
            raise ValueError(f"PipelineStep {STEP_NAME} not found for run {run_id}")
        return step

    def _get_agent_row(self) -> Optional[Agent]:
        return self.session.exec(
            select(Agent).where(Agent.name == AGENT_NAME)
        ).first()

    def _load_source_documents(
        self, project_id: uuid.UUID
    ) -> tuple[Document, Document, Document, Document]:
        def _latest(doc_type: DocumentType) -> Optional[Document]:
            return self.session.exec(
                select(Document).where(
                    Document.project_id == project_id,
                    Document.document_type == doc_type,
                ).order_by(Document.created_at.desc())
            ).first()

        arch = _latest(DocumentType.architecture_design)
        db   = _latest(DocumentType.database_design)
        api  = _latest(DocumentType.api_spec)
        fsd  = _latest(DocumentType.fsd)

        missing = [n for n, d in [("Architecture", arch), ("Database", db), ("API Spec", api), ("FSD", fsd)] if not d]
        if missing:
            raise ValueError(f"Missing source documents: {', '.join(missing)}")

        return arch, db, api, fsd  # type: ignore[return-value]

    def _log_activity(
        self, project_id: uuid.UUID, agent_row: Optional[Agent], message: str
    ) -> None:
        self.session.add(ActivityLog(
            project_id=project_id,
            agent_id=agent_row.id if agent_row else None,
            event_type=EventType.document_created,
            message=message,
        ))
