"""Gap Analysis Agent โ€” Pipeline Step 2.

Reads the requirement_summary document and detects:
  missing, unclear, conflicting requirements, missing actors, business rules, etc.
"""
import logging
import uuid
from collections import Counter
from datetime import UTC, datetime
from typing import Optional

from pydantic import BaseModel, Field
from sqlmodel import Session, select

from app.db.models import (
    ActivityLog,
    Agent,
    AgentStatus,
    Document,
    DocumentStatus,
    DocumentType,
    EventType,
    PipelineRun,
    PipelineRunStatus,
    PipelineStep,
    PipelineStepStatus,
)
from app.llm import client as _llm

logger = logging.getLogger(__name__)

AGENT_NAME = "gap-analysis-agent"
STEP_NAME = "gap_analysis"
TIMEOUT_SECONDS = 120.0

# โ”€โ”€ Output schema โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€

class _Gap(BaseModel):
    id: str = "GAP-001"
    category: str = "missing_requirement"
    severity: str = "Medium"
    description: str
    related_requirement_id: Optional[str] = None
    question: str


class GapAnalysisOutput(BaseModel):
    overall_assessment: str = ""
    completeness_score: int = 0
    gaps: list[_Gap] = Field(default_factory=list)
    recommendations: list[str] = Field(default_factory=list)


# โ”€โ”€ Prompts โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€

_SYSTEM_PROMPT = """\
You are the Gap Analysis Agent in an AI-powered software factory.
Your job is to analyze structured requirement summaries and identify gaps โ€” \
missing, unclear, conflicting, or incomplete requirements.

Rules:
- Never invent gaps that are not real. Only flag what is genuinely missing or unclear.
- Be specific. Reference the requirement ID (FR-XXX, NFR-XXX) when relevant.
- Generate one clear, answerable question for each gap.
- Rate severity honestly: Critical (blocks design), High (significant risk), \
Medium (needs clarification), Low (nice to have).
- You MUST return ONLY a valid JSON object โ€” no prose, no markdown wrapping.
"""

_TASK_TEMPLATE = """\
Analyze the following Requirement Summary and identify all gaps.
Return ONLY the JSON โ€” no explanation, no code fences.

Schema:
{{
  "overall_assessment": "2-4 sentences on the overall completeness of the requirements",
  "completeness_score": <integer 0-100, where 100 means fully complete>,
  "gaps": [
    {{
      "id": "GAP-001",
      "category": "missing_requirement|unclear_requirement|conflicting_requirement|missing_actor|missing_business_rule|missing_exception_flow|missing_integration_detail|missing_data_field|missing_security_requirement|missing_non_functional_requirement",
      "severity": "Critical|High|Medium|Low",
      "description": "specific description of the gap",
      "related_requirement_id": "FR-001 or null if not tied to a specific requirement",
      "question": "specific question to ask the stakeholder to resolve this gap"
    }}
  ],
  "recommendations": ["actionable recommendation 1"]
}}

REQUIREMENT SUMMARY:
{content}
"""


# โ”€โ”€ Markdown renderer โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€

def _render_markdown(
    data: GapAnalysisOutput,
    project_id: str,
    document_id: str,
) -> str:
    score_bar = "โ–" * (data.completeness_score // 10) + "โ–‘" * (10 - data.completeness_score // 10)

    # Summary table by category
    cat_counts = Counter(g.category for g in data.gaps)
    sev_order = {"Critical": 0, "High": 1, "Medium": 2, "Low": 3}
    sorted_gaps = sorted(data.gaps, key=lambda g: sev_order.get(g.severity, 4))

    summary_rows = ""
    for cat, count in sorted(cat_counts.items()):
        summary_rows += f"| {cat.replace('_', ' ').title()} | {count} |\n"

    gap_details = ""
    for gap in sorted_gaps:
        ref = f" โ {gap.related_requirement_id}" if gap.related_requirement_id else ""
        gap_details += f"""
### {gap.id} [{gap.severity}]{ref}

**Category:** {gap.category.replace('_', ' ').title()}

**Gap:** {gap.description}

**Question for stakeholder:** _{gap.question}_

---
"""

    recs = "\n".join(f"{i+1}. {r}" for i, r in enumerate(data.recommendations)) \
        if data.recommendations else "> No additional recommendations."
    summary_table = summary_rows if summary_rows else "| (none) | 0 |\n"

    return f"""\
# Gap Analysis Report

**Project ID:** `{project_id}`
**Document ID:** `{document_id}`
**Generated By:** Gap Analysis Agent v1.0.0
**Pipeline Step:** 2 of 10
**Status:** Draft โ’ Awaiting Review

---

## 1. Overall Assessment

{data.overall_assessment or "> No assessment produced. Review requirement inputs and re-run."}

---

## 2. Completeness Score

**{data.completeness_score}/100** `{score_bar}`

---

## 3. Gap Summary

| Category | Count |
|---|---|
{summary_table}
**Total gaps found: {len(data.gaps)}**

---

## 4. Detailed Gaps
{gap_details if gap_details else "> No gaps found. Requirements appear complete."}

## 5. Recommendations

{recs}
"""


# โ”€โ”€ Agent runner โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€

class GapAnalysisAgentRunner:
    def __init__(self, session: Session) -> None:
        self.session = session

    def run(self, run_id: uuid.UUID) -> None:
        step: PipelineStep | None = None
        agent_row: Agent | None = None

        try:
            run = self._get_run(run_id)

            # If previous step failed, abort
            if run.status == PipelineRunStatus.failed:
                logger.info("GapAnalysisAgent skipped โ€” run %s already failed", run_id)
                return

            step = self._get_step(run_id)
            agent_row = self._get_agent_row()

            # Mark running
            run.status = PipelineRunStatus.running
            run.current_step = STEP_NAME
            step.status = PipelineStepStatus.running
            step.started_at = datetime.now(UTC)
            if agent_row:
                agent_row.status = AgentStatus.working
                agent_row.updated_at = datetime.now(UTC)
            self.session.commit()

            # Load requirement_summary document
            req_summary_doc = self._load_requirement_summary(run_id)
            content = req_summary_doc.content_markdown

            raw_json = _llm.call_ollama(
                system_prompt=_SYSTEM_PROMPT,
                user_prompt=_TASK_TEMPLATE.format(content=content),
                timeout=TIMEOUT_SECONDS,
            )

            parsed = _llm.extract_json(raw_json)
            output = GapAnalysisOutput.model_validate(parsed)

            doc_id = uuid.uuid4()
            markdown = _render_markdown(output, str(run.project_id), str(doc_id))

            doc = Document(
                id=doc_id,
                project_id=run.project_id,
                document_type=DocumentType.gap_analysis_report,
                title="Gap Analysis Report",
                content_markdown=markdown,
                version=1,
                status=DocumentStatus.review,
                created_by_agent_id=agent_row.id if agent_row else None,
            )
            self.session.add(doc)
            self.session.flush()

            step.status = PipelineStepStatus.completed
            step.agent_id = agent_row.id if agent_row else None
            step.output_document_id = doc.id
            step.completed_at = datetime.now(UTC)

            # Gate 1 โ€” wait for human review before proceeding to BA Agent
            run.status = PipelineRunStatus.waiting_for_user
            run.current_step = STEP_NAME

            if agent_row:
                agent_row.status = AgentStatus.done
                agent_row.updated_at = datetime.now(UTC)

            self._log_activity(
                run.project_id, agent_row,
                f"Gap analysis complete. Gaps found: {len(output.gaps)}. Score: {output.completeness_score}/100. Awaiting Gate 1 review.",
            )
            self.session.commit()
            logger.info("GapAnalysisAgent completed run=%s doc=%s gaps=%d", run_id, doc_id, len(output.gaps))

        except Exception as exc:
            logger.exception("GapAnalysisAgent failed run=%s: %s", run_id, exc)
            self.session.rollback()

            try:
                run = self.session.get(PipelineRun, run_id)
                if run:
                    run.status = PipelineRunStatus.failed
                if step:
                    step.status = PipelineStepStatus.failed
                    step.error_message = str(exc)[:2000]
                if agent_row:
                    agent_row.status = AgentStatus.error
                    agent_row.updated_at = datetime.now(UTC)
                self.session.commit()
            except Exception:
                logger.exception("Failed to persist failure state for run=%s", run_id)

    # โ”€โ”€ helpers โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€โ”€

    def _get_run(self, run_id: uuid.UUID) -> PipelineRun:
        run = self.session.get(PipelineRun, run_id)
        if not run:
            raise ValueError(f"PipelineRun {run_id} not found")
        return run

    def _get_step(self, run_id: uuid.UUID) -> PipelineStep:
        step = self.session.exec(
            select(PipelineStep).where(
                PipelineStep.pipeline_run_id == run_id,
                PipelineStep.step_name == STEP_NAME,
            )
        ).first()
        if not step:
            raise ValueError(f"PipelineStep {STEP_NAME} not found for run {run_id}")
        return step

    def _get_agent_row(self) -> Agent | None:
        return self.session.exec(
            select(Agent).where(Agent.name == AGENT_NAME)
        ).first()

    def _load_requirement_summary(self, run_id: uuid.UUID) -> Document:
        req_step = self.session.exec(
            select(PipelineStep).where(
                PipelineStep.pipeline_run_id == run_id,
                PipelineStep.step_name == "requirement_summary",
            )
        ).first()
        if not req_step or not req_step.output_document_id:
            raise ValueError("requirement_summary step has no output document โ€” cannot run gap analysis")
        doc = self.session.get(Document, req_step.output_document_id)
        if not doc:
            raise ValueError(f"requirement_summary document {req_step.output_document_id} not found")
        return doc

    def _log_activity(self, project_id: uuid.UUID, agent_row: Agent | None, message: str) -> None:
        log = ActivityLog(
            project_id=project_id,
            agent_id=agent_row.id if agent_row else None,
            event_type=EventType.document_created,
            message=message,
        )
        self.session.add(log)
