"""Monitoring Agent -- Sprint 36.

Collects deployment runtime evidence after DevOps, probes common health
endpoints, captures Docker Compose state/logs when available, and stores a
monitoring_report document for review.
"""
import logging
import re
import shutil
import subprocess
import time
import urllib.error
import urllib.request
import uuid
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path
from typing import Optional

from sqlmodel import Session, select

from app.db.models import (
    ActivityLog,
    Agent,
    AgentStatus,
    Document,
    DocumentStatus,
    DocumentType,
    EventType,
    PipelineRun,
    PipelineRunStatus,
    PipelineStep,
    PipelineStepStatus,
    Project,
)

logger = logging.getLogger(__name__)

AGENT_NAME = "monitoring-agent"
STEP_NAME = "monitoring"
COMMAND_TIMEOUT = 90
HEALTH_TIMEOUT = 8


@dataclass
class CommandResult:
    name: str
    command: str
    status: str
    exit_code: int | None
    stdout: str
    stderr: str


@dataclass
class EndpointResult:
    url: str
    status: str
    http_status: int | None
    latency_ms: float | None
    detail: str


def _container_workspace_path(raw: str | None) -> str:
    workspace = raw or "/workspace"
    workspace = re.sub(r"^[A-Za-z]:[/\\]workspace", "/workspace", workspace, flags=re.IGNORECASE)
    if not workspace.startswith("/workspace"):
        workspace = "/workspace"
    return workspace


def _safe_name(name: str) -> str:
    return re.sub(r"[^\w\-]", "_", name)


def _short(text: str, limit: int = 5000) -> str:
    return text if len(text) <= limit else text[:limit] + "\n... output truncated ..."


def _status_from_results(commands: list[CommandResult], endpoints: list[EndpointResult]) -> str:
    command_failed = any(r.status == "failed" for r in commands)
    endpoint_passed = any(r.status == "passed" for r in endpoints)
    endpoint_failed = any(r.status == "failed" for r in endpoints)
    if command_failed or (endpoint_failed and not endpoint_passed):
        return "FAIL"
    if any(r.status == "skipped" for r in commands) or any(r.status == "skipped" for r in endpoints):
        return "PARTIAL"
    return "PASS"


def _render_monitoring_report(
    project_id: uuid.UUID,
    doc_id: uuid.UUID,
    app_dir: Path,
    commands: list[CommandResult],
    endpoints: list[EndpointResult],
    build_report: Document | None,
) -> str:
    overall = _status_from_results(commands, endpoints)
    passed = sum(1 for r in endpoints if r.status == "passed")
    failed = sum(1 for r in endpoints if r.status == "failed")
    skipped = sum(1 for r in endpoints if r.status == "skipped")
    command_rows = "\n".join(
        f"| {r.name} | `{r.command}` | {r.status.upper()} | {r.exit_code if r.exit_code is not None else '-'} |"
        for r in commands
    )
    endpoint_rows = "\n".join(
        f"| `{r.url}` | {r.status.upper()} | {r.http_status if r.http_status is not None else '-'} | "
        f"{round(r.latency_ms, 1) if r.latency_ms is not None else '-'} | {r.detail} |"
        for r in endpoints
    )
    command_blocks = "\n".join(
        f"""### {r.name}

**Command:** `{r.command}`  
**Status:** {r.status.upper()}  
**Exit code:** {r.exit_code if r.exit_code is not None else "-"}

```text
STDOUT:
{_short(r.stdout)}

STDERR:
{_short(r.stderr)}
```
"""
        for r in commands
    )
    build_ref = "No build report document found."
    if build_report:
        build_ref = f"`{build_report.id}` - {build_report.title}"

    return f"""# Monitoring Report

**Project ID:** `{project_id}`  
**Document ID:** `{doc_id}`  
**Generated By:** Monitoring Agent  
**Pipeline Step:** 11 of 12  
**Generated At:** {datetime.now(UTC).strftime('%Y-%m-%d %H:%M UTC')}  
**Overall Status:** {overall}

## Summary

| Metric | Count |
|---|---:|
| Endpoints passed | {passed} |
| Endpoints failed | {failed} |
| Endpoints skipped | {skipped} |

**Workspace:** `{app_dir}`

**Build Report Reference:** {build_ref}

## Endpoint Checks

| URL | Status | HTTP Status | Latency ms | Detail |
|---|---|---:|---:|---|
{endpoint_rows}

## Runtime Commands

| Check | Command | Status | Exit Code |
|---|---|---|---:|
{command_rows}

## Command Output

{command_blocks}
"""


class MonitoringAgentRunner:
    def __init__(self, session: Session) -> None:
        self.session = session

    def run(self, run_id: uuid.UUID) -> None:
        step: Optional[PipelineStep] = None
        agent_row: Optional[Agent] = None

        try:
            run = self._get_run(run_id)
            if run.status == PipelineRunStatus.failed:
                logger.info("MonitoringAgent skipped -- run %s already failed", run_id)
                return

            step = self._get_step(run_id)
            agent_row = self._get_agent_row()

            run.status = PipelineRunStatus.running
            run.current_step = STEP_NAME
            step.status = PipelineStepStatus.running
            step.started_at = datetime.now(UTC)
            if agent_row:
                agent_row.status = AgentStatus.working
                agent_row.updated_at = datetime.now(UTC)
            self.session.commit()

            app_dir = self._get_app_dir(run.project_id)
            build_report = self._latest_document(run.project_id, DocumentType.build_report)
            api_spec = self._latest_document(run.project_id, DocumentType.api_spec)

            commands = self._collect_runtime_commands(app_dir)
            endpoints = self._probe_endpoints(api_spec.content_markdown if api_spec else "")

            doc_id = uuid.uuid4()
            markdown = _render_monitoring_report(
                project_id=run.project_id,
                doc_id=doc_id,
                app_dir=app_dir,
                commands=commands,
                endpoints=endpoints,
                build_report=build_report,
            )
            overall = _status_from_results(commands, endpoints)
            document = Document(
                id=doc_id,
                project_id=run.project_id,
                document_type=DocumentType.monitoring_report,
                title=f"Monitoring Report -- {overall}",
                content_markdown=markdown,
                version=1,
                status=DocumentStatus.review,
                created_by_agent_id=agent_row.id if agent_row else None,
            )
            self.session.add(document)
            self.session.flush()

            step.status = PipelineStepStatus.completed
            step.agent_id = agent_row.id if agent_row else None
            step.output_document_id = document.id
            step.completed_at = datetime.now(UTC)
            run.status = PipelineRunStatus.waiting_for_user
            run.current_step = STEP_NAME

            if agent_row:
                agent_row.status = AgentStatus.done
                agent_row.updated_at = datetime.now(UTC)

            self._log_activity(
                run.project_id,
                agent_row,
                f"Monitoring completed with status {overall}; probed {len(endpoints)} endpoints.",
            )
            self.session.commit()

            from app.agents._workspace import write_workspace_docs

            write_workspace_docs(self.session, run.project_id, {"monitoring_report.md": markdown})
            logger.info("MonitoringAgent completed run=%s report=%s status=%s", run_id, doc_id, overall)

        except Exception as exc:
            logger.exception("MonitoringAgent failed run=%s: %s", run_id, exc)
            self.session.rollback()
            try:
                run = self.session.get(PipelineRun, run_id)
                if run:
                    run.status = PipelineRunStatus.failed
                if step:
                    step.status = PipelineStepStatus.failed
                    step.error_message = str(exc)[:2000]
                    step.completed_at = datetime.now(UTC)
                if agent_row:
                    agent_row.status = AgentStatus.error
                    agent_row.updated_at = datetime.now(UTC)
                self.session.commit()
            except Exception:
                logger.exception("Failed to persist Monitoring failure state for run=%s", run_id)

    def _collect_runtime_commands(self, app_dir: Path) -> list[CommandResult]:
        if not app_dir.exists():
            return [
                CommandResult(
                    name="Generated App Directory",
                    command=f"test -d {app_dir}",
                    status="failed",
                    exit_code=None,
                    stdout="",
                    stderr=f"Directory not found: {app_dir}",
                )
            ]
        compose = self._compose_file(app_dir)
        if not compose:
            return [
                CommandResult(
                    name="Docker Compose Discovery",
                    command=f"find compose file in {app_dir}",
                    status="skipped",
                    exit_code=None,
                    stdout="",
                    stderr="No docker-compose.yml or compose.yml found.",
                )
            ]
        if not shutil.which("docker"):
            return [
                CommandResult(
                    name="Docker CLI",
                    command="docker --version",
                    status="skipped",
                    exit_code=None,
                    stdout="",
                    stderr="Docker CLI is not available in this runtime.",
                )
            ]
        return [
            self._run_command("Compose Services", ["docker", "compose", "-f", str(compose), "ps"], app_dir),
            self._run_command("Compose Logs", ["docker", "compose", "-f", str(compose), "logs", "--tail", "80"], app_dir),
        ]

    def _probe_endpoints(self, api_spec: str) -> list[EndpointResult]:
        urls = self._candidate_urls(api_spec)
        return [self._probe_url(url) for url in urls]

    def _candidate_urls(self, api_spec: str) -> list[str]:
        urls = [
            "http://localhost:8000/health",
            "http://localhost:8000/api/v1/health",
            "http://localhost:3000",
            "http://localhost",
        ]
        paths = sorted(set(re.findall(r"`(/[^`\s]+)`", api_spec)))
        for path in paths:
            clean = path.split("{", 1)[0].rstrip("/") or path
            if clean and clean not in {"/health", "/api/v1/health"}:
                urls.append(f"http://localhost:8000{clean}")
        seen: set[str] = set()
        deduped: list[str] = []
        for url in urls:
            if url not in seen:
                deduped.append(url)
                seen.add(url)
        return deduped[:8]

    def _probe_url(self, url: str) -> EndpointResult:
        started = time.perf_counter()
        try:
            with urllib.request.urlopen(url, timeout=HEALTH_TIMEOUT) as response:
                latency = (time.perf_counter() - started) * 1000
                status = getattr(response, "status", None)
                if status and 200 <= status < 500:
                    return EndpointResult(url, "passed", status, latency, "Endpoint responded.")
                return EndpointResult(url, "failed", status, latency, f"Unexpected HTTP status {status}.")
        except urllib.error.HTTPError as exc:
            latency = (time.perf_counter() - started) * 1000
            if exc.code < 500:
                return EndpointResult(url, "passed", exc.code, latency, f"HTTP {exc.code}: {exc.reason}")
            return EndpointResult(url, "failed", exc.code, latency, f"HTTP {exc.code}: {exc.reason}")
        except Exception as exc:
            latency = (time.perf_counter() - started) * 1000
            return EndpointResult(url, "failed", None, latency, str(exc))

    def _run_command(self, name: str, command: list[str], cwd: Path) -> CommandResult:
        try:
            completed = subprocess.run(
                command,
                cwd=str(cwd),
                text=True,
                capture_output=True,
                timeout=COMMAND_TIMEOUT,
                check=False,
            )
            return CommandResult(
                name=name,
                command=" ".join(command),
                status="passed" if completed.returncode == 0 else "failed",
                exit_code=completed.returncode,
                stdout=completed.stdout,
                stderr=completed.stderr,
            )
        except subprocess.TimeoutExpired as exc:
            return CommandResult(
                name=name,
                command=" ".join(command),
                status="failed",
                exit_code=None,
                stdout=exc.stdout or "",
                stderr=f"Timed out after {COMMAND_TIMEOUT} seconds. {exc.stderr or ''}",
            )
        except OSError as exc:
            return CommandResult(
                name=name,
                command=" ".join(command),
                status="failed",
                exit_code=None,
                stdout="",
                stderr=str(exc),
            )

    def _compose_file(self, app_dir: Path) -> Path | None:
        for name in ("docker-compose.yml", "docker-compose.yaml", "compose.yml", "compose.yaml"):
            candidate = app_dir / name
            if candidate.exists():
                return candidate
        return None

    def _get_app_dir(self, project_id: uuid.UUID) -> Path:
        project = self.session.get(Project, project_id)
        workspace = _container_workspace_path(project.workspace_path if project else None)
        safe_name = _safe_name(project.name if project else "project")
        return Path(workspace) / safe_name / "generated_app"

    def _get_run(self, run_id: uuid.UUID) -> PipelineRun:
        run = self.session.get(PipelineRun, run_id)
        if not run:
            raise ValueError(f"PipelineRun {run_id} not found")
        return run

    def _get_step(self, run_id: uuid.UUID) -> PipelineStep:
        step = self.session.exec(
            select(PipelineStep).where(
                PipelineStep.pipeline_run_id == run_id,
                PipelineStep.step_name == STEP_NAME,
            )
        ).first()
        if not step:
            raise ValueError(f"PipelineStep {STEP_NAME} not found for run {run_id}")
        return step

    def _get_agent_row(self) -> Optional[Agent]:
        return self.session.exec(select(Agent).where(Agent.name == AGENT_NAME)).first()

    def _latest_document(self, project_id: uuid.UUID, doc_type: DocumentType) -> Optional[Document]:
        return self.session.exec(
            select(Document)
            .where(Document.project_id == project_id, Document.document_type == doc_type)
            .order_by(Document.created_at.desc())  # type: ignore[union-attr]
        ).first()

    def _log_activity(self, project_id: uuid.UUID, agent_row: Optional[Agent], message: str) -> None:
        self.session.add(ActivityLog(
            project_id=project_id,
            agent_id=agent_row.id if agent_row else None,
            event_type=EventType.document_created,
            message=message,
        ))
