"""QA Agent -- Sprint 34.

Generates executable test files for the generated application workspace, runs the
test commands that are available in the current environment, and stores a
test_report document plus docs/test_report.md in the project workspace.
"""
import logging
import os
import re
import shutil
import subprocess
import sys
import uuid
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path
from typing import Optional

from sqlmodel import Session, select

from app.db.models import (
    ActivityLog,
    Agent,
    AgentStatus,
    Document,
    DocumentStatus,
    DocumentType,
    EventType,
    PipelineRun,
    PipelineRunStatus,
    PipelineStep,
    PipelineStepStatus,
    Project,
)

logger = logging.getLogger(__name__)

AGENT_NAME = "qa-agent"
STEP_NAME = "test_cases"

PYTEST_TIMEOUT_SECONDS = 120
PLAYWRIGHT_TIMEOUT_SECONDS = 180


@dataclass
class TestCommandResult:
    name: str
    command: str
    status: str
    exit_code: int | None
    stdout: str
    stderr: str


def _sanitize_project_name(name: str) -> str:
    return re.sub(r"[^\w\-]", "_", name)


def _container_workspace_path(raw: str | None) -> str:
    workspace = raw or "/workspace"
    workspace = re.sub(r"^[A-Za-z]:[/\\]workspace", "/workspace", workspace, flags=re.IGNORECASE)
    if not workspace.startswith("/workspace"):
        workspace = "/workspace"
    return workspace


def _safe_write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def _short(text: str, limit: int = 5000) -> str:
    if len(text) <= limit:
        return text
    return text[:limit] + "\n... output truncated ..."


def _find_source_files(app_dir: Path) -> list[Path]:
    if not app_dir.exists():
        return []
    ignored_parts = {"node_modules", ".git", "dist", "build", "__pycache__"}
    source_exts = {".py", ".ts", ".tsx", ".js", ".jsx", ".json", ".yaml", ".yml", ".toml"}
    files: list[Path] = []
    for path in app_dir.rglob("*"):
        if not path.is_file():
            continue
        if any(part in ignored_parts for part in path.parts):
            continue
        if path.suffix.lower() in source_exts or path.name in {"Dockerfile", "requirements.txt"}:
            files.append(path)
    return sorted(files)


def _extract_api_refs(api_spec: str) -> list[str]:
    refs = sorted(set(re.findall(r"\bAPI-\d{3}\b", api_spec)))
    return refs or ["API-001"]


def _extract_screen_refs(screen_spec: str) -> list[str]:
    refs = sorted(set(re.findall(r"\bUI-\d{3}\b", screen_spec)))
    return refs or ["UI-001"]


def _render_pytest_workspace_test() -> str:
    return '''"""Generated by AI-SDLC QA Agent.

Static smoke checks for generated source files.
"""
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
APP_DIR = ROOT / "generated_app"


def test_generated_app_directory_exists():
    assert APP_DIR.exists(), f"generated_app directory is missing: {APP_DIR}"


def test_generated_app_contains_source_files():
    source_exts = {".py", ".ts", ".tsx", ".js", ".jsx", ".json", ".yaml", ".yml", ".toml"}
    files = [
        p for p in APP_DIR.rglob("*")
        if p.is_file()
        and "node_modules" not in p.parts
        and "__pycache__" not in p.parts
        and (p.suffix in source_exts or p.name in {"Dockerfile", "requirements.txt"})
    ]
    assert files, "No generated source/config files found"


def test_generated_files_are_not_empty():
    empty = [
        str(p.relative_to(APP_DIR))
        for p in APP_DIR.rglob("*")
        if p.is_file()
        and "node_modules" not in p.parts
        and "__pycache__" not in p.parts
        and p.stat().st_size == 0
    ]
    assert not empty, f"Generated files must not be empty: {empty}"
'''


def _render_pytest_api_contract_test(api_refs: list[str]) -> str:
    refs_literal = repr(api_refs)
    return f'''"""Generated by AI-SDLC QA Agent.

Static API contract checks derived from docs/api_spec.md.
"""
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
API_SPEC = ROOT / "docs" / "api_spec.md"
EXPECTED_API_REFS = {refs_literal}


def test_api_spec_document_exists():
    assert API_SPEC.exists(), f"Missing API spec document: {{API_SPEC}}"


def test_expected_api_references_are_documented():
    content = API_SPEC.read_text(encoding="utf-8")
    missing = [ref for ref in EXPECTED_API_REFS if ref not in content]
    assert not missing, f"API references missing from api_spec.md: {{missing}}"
'''


def _render_playwright_smoke_test(screen_refs: list[str]) -> str:
    refs = ", ".join(screen_refs)
    return f'''import {{ test, expect }} from "@playwright/test";

// Generated by AI-SDLC QA Agent.
// Screen refs covered by this smoke spec: {refs}

test("generated frontend can load", async ({{ page }}) => {{
  const baseURL = process.env.PLAYWRIGHT_BASE_URL || "http://localhost:3000";
  await page.goto(baseURL);
  await expect(page.locator("body")).toBeVisible();
}});
'''


def _render_test_report(
    project_id: uuid.UUID,
    doc_id: uuid.UUID,
    generated_files: list[str],
    source_file_count: int,
    results: list[TestCommandResult],
) -> str:
    now = datetime.now(UTC).strftime("%Y-%m-%d %H:%M UTC")
    passed = sum(1 for r in results if r.status == "passed")
    failed = sum(1 for r in results if r.status == "failed")
    skipped = sum(1 for r in results if r.status == "skipped")
    overall = "PASS" if failed == 0 else "FAIL"

    file_rows = "\n".join(f"| `{path}` | generated |" for path in generated_files)
    result_rows = "\n".join(
        f"| {r.name} | `{r.command}` | {r.status.upper()} | {r.exit_code if r.exit_code is not None else '-'} |"
        for r in results
    )
    output_blocks = "\n".join(
        f"""### {r.name}

**Command:** `{r.command}`  
**Status:** {r.status.upper()}  
**Exit code:** {r.exit_code if r.exit_code is not None else "-"}

```text
STDOUT:
{_short(r.stdout)}

STDERR:
{_short(r.stderr)}
```
"""
        for r in results
    )

    return f"""# Test Report

**Project ID:** `{project_id}`  
**Document ID:** `{doc_id}`  
**Generated By:** QA Agent  
**Pipeline Step:** 9 of 12  
**Generated At:** {now}  
**Overall Status:** {overall}

---

## Summary

| Metric | Count |
|---|---:|
| Generated app source files scanned | {source_file_count} |
| Test files generated | {len(generated_files)} |
| Commands passed | {passed} |
| Commands failed | {failed} |
| Commands skipped | {skipped} |

## Generated Test Files

| File | Status |
|---|---|
{file_rows}

## Command Results

| Runner | Command | Status | Exit Code |
|---|---|---|---:|
{result_rows}

## Runner Output

{output_blocks}
"""


class QAAgentRunner:
    def __init__(self, session: Session) -> None:
        self.session = session

    def run(self, run_id: uuid.UUID) -> None:
        step: Optional[PipelineStep] = None
        agent_row: Optional[Agent] = None

        try:
            run = self._get_run(run_id)
            if run.status == PipelineRunStatus.failed:
                logger.info("QAAgent skipped -- run %s already failed", run_id)
                return

            step = self._get_step(run_id)
            agent_row = self._get_agent_row()

            run.status = PipelineRunStatus.running
            run.current_step = STEP_NAME
            step.status = PipelineStepStatus.running
            step.started_at = datetime.now(UTC)
            if agent_row:
                agent_row.status = AgentStatus.working
                agent_row.updated_at = datetime.now(UTC)
            self.session.commit()

            project_root = self._get_project_root(run.project_id)
            app_dir = project_root / "generated_app"
            docs_dir = project_root / "docs"
            tests_dir = project_root / "tests"

            api_doc, screen_doc = self._load_contract_documents(run.project_id)
            api_refs = _extract_api_refs(api_doc.content_markdown if api_doc else "")
            screen_refs = _extract_screen_refs(screen_doc.content_markdown if screen_doc else "")

            source_files = _find_source_files(app_dir)
            generated_files = self._write_test_files(tests_dir, api_refs, screen_refs)

            results = self._run_tests(project_root)

            doc_id = uuid.uuid4()
            markdown = _render_test_report(
                project_id=run.project_id,
                doc_id=doc_id,
                generated_files=generated_files,
                source_file_count=len(source_files),
                results=results,
            )

            report_doc = Document(
                id=doc_id,
                project_id=run.project_id,
                document_type=DocumentType.test_report,
                title="Test Report",
                content_markdown=markdown,
                version=1,
                status=DocumentStatus.review,
                created_by_agent_id=agent_row.id if agent_row else None,
            )
            self.session.add(report_doc)
            self.session.flush()

            step.status = PipelineStepStatus.completed
            step.agent_id = agent_row.id if agent_row else None
            step.output_document_id = report_doc.id
            step.completed_at = datetime.now(UTC)

            run.status = PipelineRunStatus.waiting_for_user
            run.current_step = STEP_NAME

            if agent_row:
                agent_row.status = AgentStatus.done
                agent_row.updated_at = datetime.now(UTC)

            failed = sum(1 for r in results if r.status == "failed")
            passed = sum(1 for r in results if r.status == "passed")
            skipped = sum(1 for r in results if r.status == "skipped")
            self._log_activity(
                run.project_id,
                agent_row,
                (
                    f"QA generated {len(generated_files)} test file(s), scanned "
                    f"{len(source_files)} source file(s), commands: {passed} passed, "
                    f"{failed} failed, {skipped} skipped. Awaiting QA review."
                ),
            )
            self.session.commit()

            from app.agents._workspace import write_workspace_docs

            write_workspace_docs(self.session, run.project_id, {"test_report.md": markdown})
            logger.info(
                "QAAgent completed run=%s report=%s generated_tests=%d failed_commands=%d",
                run_id, doc_id, len(generated_files), failed,
            )

        except Exception as exc:
            logger.exception("QAAgent failed run=%s: %s", run_id, exc)
            self.session.rollback()
            try:
                run = self.session.get(PipelineRun, run_id)
                if run:
                    run.status = PipelineRunStatus.failed
                if step:
                    step.status = PipelineStepStatus.failed
                    step.error_message = str(exc)[:2000]
                    step.completed_at = datetime.now(UTC)
                if agent_row:
                    agent_row.status = AgentStatus.error
                    agent_row.updated_at = datetime.now(UTC)
                self.session.commit()
            except Exception:
                logger.exception("Failed to persist QA failure state for run=%s", run_id)

    def _write_test_files(self, tests_dir: Path, api_refs: list[str], screen_refs: list[str]) -> list[str]:
        files = {
            "tests/unit/test_generated_workspace.py": _render_pytest_workspace_test(),
            "tests/api/test_api_contract_static.py": _render_pytest_api_contract_test(api_refs),
            "tests/e2e/test_smoke.spec.ts": _render_playwright_smoke_test(screen_refs),
        }
        for rel_path, content in files.items():
            _safe_write(tests_dir.parent / rel_path, content)
        return sorted(files.keys())

    def _run_tests(self, project_root: Path) -> list[TestCommandResult]:
        results: list[TestCommandResult] = []
        pytest_targets = ["tests/unit", "tests/api"]

        pytest_cmd = [sys.executable, "-m", "pytest", *pytest_targets]
        results.append(self._run_command("pytest", pytest_cmd, project_root, PYTEST_TIMEOUT_SECONDS))

        frontend_dir = project_root / "generated_app" / "frontend"
        playwright_configured = (project_root / "tests" / "e2e").exists() and (
            (frontend_dir / "package.json").exists() or (project_root / "generated_app" / "package.json").exists()
        )
        npx = shutil.which("npx.cmd") or shutil.which("npx")
        if playwright_configured and npx:
            results.append(self._run_command(
                "playwright",
                [npx, "--no-install", "playwright", "test", "tests/e2e"],
                project_root,
                PLAYWRIGHT_TIMEOUT_SECONDS,
            ))
        else:
            results.append(TestCommandResult(
                name="playwright",
                command="npx --no-install playwright test tests/e2e",
                status="skipped",
                exit_code=None,
                stdout="Playwright skipped: generated frontend package or npx is not available.",
                stderr="",
            ))

        return results

    def _run_command(
        self,
        name: str,
        command: list[str],
        cwd: Path,
        timeout: int,
    ) -> TestCommandResult:
        try:
            completed = subprocess.run(
                command,
                cwd=str(cwd),
                capture_output=True,
                text=True,
                timeout=timeout,
                check=False,
            )
            return TestCommandResult(
                name=name,
                command=" ".join(command),
                status="passed" if completed.returncode == 0 else "failed",
                exit_code=completed.returncode,
                stdout=completed.stdout,
                stderr=completed.stderr,
            )
        except FileNotFoundError as exc:
            return TestCommandResult(
                name=name,
                command=" ".join(command),
                status="skipped",
                exit_code=None,
                stdout=f"Skipped: {exc}",
                stderr="",
            )
        except subprocess.TimeoutExpired as exc:
            return TestCommandResult(
                name=name,
                command=" ".join(command),
                status="failed",
                exit_code=None,
                stdout=exc.stdout or "",
                stderr=f"Timed out after {timeout} seconds. {exc.stderr or ''}",
            )

    def _get_project_root(self, project_id: uuid.UUID) -> Path:
        project = self.session.get(Project, project_id)
        workspace = _container_workspace_path(project.workspace_path if project else None)
        safe_name = _sanitize_project_name(project.name if project else "project")
        return Path(workspace) / safe_name

    def _get_run(self, run_id: uuid.UUID) -> PipelineRun:
        run = self.session.get(PipelineRun, run_id)
        if not run:
            raise ValueError(f"PipelineRun {run_id} not found")
        return run

    def _get_step(self, run_id: uuid.UUID) -> PipelineStep:
        step = self.session.exec(
            select(PipelineStep).where(
                PipelineStep.pipeline_run_id == run_id,
                PipelineStep.step_name == STEP_NAME,
            )
        ).first()
        if not step:
            raise ValueError(f"PipelineStep {STEP_NAME} not found for run {run_id}")
        return step

    def _get_agent_row(self) -> Optional[Agent]:
        return self.session.exec(select(Agent).where(Agent.name == AGENT_NAME)).first()

    def _load_contract_documents(self, project_id: uuid.UUID) -> tuple[Optional[Document], Optional[Document]]:
        def _latest(doc_type: DocumentType) -> Optional[Document]:
            return self.session.exec(
                select(Document)
                .where(
                    Document.project_id == project_id,
                    Document.document_type == doc_type,
                )
                .order_by(Document.created_at.desc())  # type: ignore[union-attr]
            ).first()

        return _latest(DocumentType.api_spec), _latest(DocumentType.screen_spec)

    def _log_activity(self, project_id: uuid.UUID, agent_row: Optional[Agent], message: str) -> None:
        self.session.add(ActivityLog(
            project_id=project_id,
            agent_id=agent_row.id if agent_row else None,
            event_type=EventType.document_created,
            message=message,
        ))
